### ISSUE TITLE
ERROR IN ORF_PROB.TSV

### ISSUE THREAD

**Issue by parsboy66** [liguowang/cpat#5]
thanks for the nice job, 

on the conda env , CPAT version 3.0.4 already installed and i am using python 3.7. by running cpat.py i am getting this error while itaking care of all input files.

2022-11-16 03:05:48 [INFO]  Calculate coding probability ...
Fatal error: unable to open the base package

2022-11-16 03:05:48 [INFO]  Removing file "/hpcnfs/output1.ORF_info.tsv"
2022-11-16 03:05:48 [INFO]  Select ORF with the highest coding probability ...
Traceback (most recent call last):
  File "/hpcnfs/home/.local/bin/cpat.py", line 237, in <module>
    main()
  File "/hpcnfs/home/.local/bin/cpat.py", line 213, in main
    for l in open((options.out_file + '.ORF_prob.tsv'), 'r'):
FileNotFoundError: [Errno 2] No such file or directory: '/hpcnfs/output1.ORF_prob.tsv'

could you pleaae help me overcome it?
Thanks

**Comment by cyli0421** [comment]
How do you solve this problem. I have met this problem, too.

**Comment by rugilemat** [comment]
Hi, I'm having  the same issue:

```
 152915 sequences finished

2025-03-03 12:12:11 [INFO]  Calculate coding probability ...
/bin/sh: Rscript: command not found
2025-03-03 12:12:11 [INFO]  Removing file "/scratch/paper/directrna/direct_rna_cpat.ORF_info.tsv"
2025-03-03 12:12:11 [INFO]  Select ORF with the highest coding probability ...
Traceback (most recent call last):
  File "/home1/.conda/envs/CPAT/bin/cpat.py", line 237, in <module>
    main()
  File "/home1/.conda/envs/CPAT/bin/cpat.py", line 213, in main
    for l in open((options.out_file + '.ORF_prob.tsv'), 'r'):
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/paper/directrna/direct_rna_cpat.ORF_prob.tsv'
```

How did you manage to solve it?
