### ISSUE TITLE
ORF_prob.tsv

### ISSUE THREAD

**Issue by kittyBS** [liguowang/cpat#7]
Hello,
Thank you for the tool.
Before installing CPAT, I created the environment with Python 3.11 and installed version 3.0.4 with pip install CPAT. I downloaded the Human_Hexamer.tsv and Human_logitModel.RData files from the link you provided on the tutorial page.
When I run the code below, I get error '''2024-01-17 11:23:49 [INFO]  Calculate coding probability ...
/bin/sh: 1: Rscript: not found
2024-01-17 11:23:49 [INFO]  Removing file "/archive/yildize/alotaibi_lab/human_data/cpat/output.ORF_info.tsv"
2024-01-17 11:23:49 [INFO]  Select ORF with the highest coding probability ...
Traceback (most recent call last):
  File "/home/yildize/.conda/envs/cpat/bin/cpat.py", line 237, in <module>
    main()
  File "/home/yildize/.conda/envs/cpat/bin/cpat.py", line 213, in main
    for l in open((options.out_file + '.ORF_prob.tsv'), 'r'):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'''.
 When I run the "cpat.py -x /archive/yildize/alotaibi_lab/human_data/cpat/Human_Hexamer.tsv --antisense -d /archive/yildize/alotaibi_lab/human_data/cpat/Human_logitModel.RData --top-orf=5 -g https://data.cyverse.org/dav-anon/iplant/home/liguow/CPAT/Human_test_coding_mRNA.fa -o output2" code on the tutorial page to see if there is a problem caused by me, I get the same error. Can you help me solve this problem?
 My code "cpat.py -x /archive/yildize/alotaibi_lab/human_data/cpat/Human_Hexamer.tsv --antisense -d /archive/yildize/alotaibi_lab/human_data/cpat/Human_logitModel.RData --top-orf=5 -g /archive/yildize/alotaibi_lab/human_data/cpat/filtered_transdecoder.fasta -o /archive/yildize/alotaibi_lab/human_data/cpat/output"
Thank you in advance for your interest.

**Comment by liguowang** [comment]
I could not tell where the problem is based on the information you provided. Please re-post this issue with the full error message.
